steps:
  # Step 1: Wait for specific triggers to finish (max 5 minutes)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        echo "⏳ Checking if selected triggers are running before starting build..."

        # 👇 List of trigger names to wait for
        WATCHED_TRIGGERS=("trigger-1" "trigger-3")
        TRIGGER_PATTERN="$$(IFS=\|; echo "$${WATCHED_TRIGGERS[*]}")"

        TIMEOUT=300  # 5 minutes
        START_TIME=$$(date +%s)

        while true; do
          echo "🔍 Fetching ongoing builds from asia-south1..."
          ALL_BUILDS=$$(gcloud builds list --ongoing --region=asia-south1 \
            --format="table(id,createTime,status,substitutions.TRIGGER_NAME)")

          echo "$$ALL_BUILDS"

          RUNNING_BUILDS=$$(echo "$$ALL_BUILDS" | grep -iE "$$TRIGGER_PATTERN" || true)

          if [[ -z "$$RUNNING_BUILDS" ]]; then
            echo "✅ None of the watched triggers are running. Proceeding..."
            break
          fi

          echo "🔄 Found running builds for watched triggers:"
          echo "$$RUNNING_BUILDS"

          CURRENT_TIME=$$(date +%s)
          ELAPSED=$$((CURRENT_TIME - START_TIME))

          if [[ $$ELAPSED -ge $$TIMEOUT ]]; then
            echo "⚠️ Timeout reached (5 minutes). Proceeding with build anyway..."
            break
          fi

          echo "⏱ Waiting 30 seconds before checking again..."
          sleep 30
        done

  # Step 2: Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build', '-t',
        'asia-south1-docker.pkg.dev/divine-course-470809-f6/deploy-to-cloudrun/cloudrun-app:latest',
        '.'
      ]

  # Step 3: Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-south1-docker.pkg.dev/divine-course-470809-f6/deploy-to-cloudrun/cloudrun-app:latest'
      ]

timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY
